image: gcc

before_script:
  - apt-get update --yes
  - apt-get install --yes cmake
  - apt-get install --yes libgtest-dev
variables:
  BIN_NAME: YSNP

stages:
  - test_style
  - build

test_style:
  stage: test_style
  script:
    - ./linters/run.sh

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
  artifacts:
    paths:
      - "build"
