image: gcc

before_script:
  - apt-get update --yes
  - apt-get install --yes cmake
  - apt-get install --yes libgtest-dev


stages:
  - test_style
  - build
  - test_bin
  - test_mem

test_style:
  stage: test_style
  script:
    - ./linters/run.sh

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
  artifacts:
    paths:
      - "build"

test_bin:
  stage: test_bin
  script:
    - cd build
    - ctest -V -R

test_mem:
  stage: test_mem
  script:
    - cd build
    - ./valgrind/run.sh

