image: gcc

before_script:
  - apt-get update --yes
  - apt-get install --yes cmake
  - apt-get install --yes libgtest-dev
  - apt-get install libgmock-dev
variables:
  BIN_NAME: YSNP

  VALGRIND_LOG: "valgrind.log"
  NO_LOST_PATTERN: "All heap blocks were freed -- no leaks are possible"
  NO_ERROR_PATTERN: "ERROR SUMMARY: 0 errors"

stages:
  - pages
  - test_style
  - build
  - test_bin
  - test_mem

pages:
  stage: pages
  script:
    # Устанавливаем пакеты
    - apt-get -y install doxygen
    - apt-get -y install graphviz
    # Прогоняем Doxygen
    - doxygen doc/Doxyfile.cfg
    # Диплоим
    - mv doc/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master

test_style:
  stage: test_style
  script:
    - ./linters/run.sh

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
  artifacts:
    paths:
      - "build"

test_bin:
  stage: test_bin
  script:
    - cd build
    - ctest -V -R

test_mem:
  stage: test_mem
  script:
    - apt-get update && apt-get install -y valgrind
    - cd build/project/DataBases/tests
    - valgrind --tool=memcheck --leak-check=summary --log-file=${VALGRIND_LOG} --leak-check=full --show-leak-kinds=all ./UtilsTests
    - export NO_LOST=$(grep "${NO_LOST_PATTERN}" ${VALGRIND_LOG})
    - export NO_ERROR=$(grep "${NO_ERROR_PATTERN}" ${VALGRIND_LOG})
    - if [ -z "${NO_LOST}" ] || [ -z "${NO_ERROR}" ]; then cat ${VALGRIND_LOG}; exit 1; fi



