//
// Created by Ivan Gorshkov on 23.11.2020.
//

#ifndef YSNP_CLOUD_PROJECT_DATABASES_INTERNALDB_INCLUDE_SQLITEQUERY_H_
#define YSNP_CLOUD_PROJECT_DATABASES_INTERNALDB_INCLUDE_SQLITEQUERY_H_

#endif //YSNP_CLOUD_PROJECT_DATABASES_INTERNALDB_INCLUDE_SQLITEQUERY_H_
